# 线性代数 Linear Algebra

## 奇异值 Singular Value
[推导](https://zhuanlan.zhihu.com/p/269329826#:~:text=%E8%BF%99%E5%B0%B1%E5%BC%95%E5%87%BA%E4%BA%86SVD%E5%A5%87%E5%BC%82%E5%80%BC%E7%9A%84%E5%88%86%E8%A7%A3%EF%BC%9A%20%E8%80%83%E8%99%91%E4%B8%80%E4%B8%AA%E7%9F%A9%E9%98%B5M%EF%BC%8C%E5%A4%A7%E5%B0%8F%E4%B8%BAm%2An%20%E9%82%A3%E4%B9%88%E6%8E%A8%E5%AF%BC%E7%9A%84%E6%AD%A5%E9%AA%A4%E4%B8%BA%EF%BC%9A%20%E6%AD%A5%E9%AA%A4%E4%B8%80%EF%BC%9A%20%E5%8F%96%20M%5ETM,%E5%85%88%E5%8F%98%E6%88%90%E4%B8%80%E4%B8%AA%E6%96%B9%E9%98%B5%EF%BC%8C%E6%B3%A8%E6%84%8F%E8%BF%99%E4%B8%AA%E7%9B%B8%E4%B9%98%E5%90%8E%E5%BE%97%E5%88%B0%E7%9A%84%E7%9F%A9%E9%98%B5%E8%BF%98%E6%98%AF%E5%AF%B9%E7%A7%B0%E7%9A%84%E3%80%82%20%E6%AD%A5%E9%AA%A4%E4%BA%8C%EF%BC%9A%20%E5%AF%B9%20M%5ETM%2C%E6%9D%A5%E8%AF%B4%EF%BC%8C%E5%AD%98%E5%9C%A8%E4%B8%80%E4%B8%AA%E6%AD%A3%E4%BA%A4%E7%9F%A9%E9%98%B5Q%E4%BD%BF%E5%BE%97%20Q%5ETM%5ETMQ%3Ddiag%20%28lambda_1%2Clambda_2...%29)

In [2]:
from rich import print
import numpy as np

a = np.array([[1, 0, 1], [0, 1, 1], [0, 0, 0]])
U, S, VT = np.linalg.svd(a)  # a = U @ np.diag(S) @ VT
print(U, S, VT, sep='\n\n')

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

[ 1.73205081  1.         -0.        ]

[[ 4.08248290e-01  4.08248290e-01  8.16496581e-01]
 [-7.07106781e-01  7.07106781e-01  2.22044605e-16]
 [ 5.77350269e-01  5.77350269e-01 -5.77350269e-01]]